export const apiBaseUrl = 'https://api.themoviedb.org/3/';
export const token = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2ZjQ2OTY0MTM1MWUwMWNiMjc5ZDYyZGMwY2ExZDRmZiIsInN1YiI6IjY0YzRjMzRkZWVjNWI1MDBlMjNiNzczNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.fjgUg2088aKOkO0Vps_urKGtziy-K08PRh1PwLZ7ZXM';
